logging:
    level:
        org.springframework.web: INFO
        org.springframework.core.codec: INFO
        org.springframework.ai: INFO
        org.springframework: INFO
slack:
    botToken: ${SLACK_BOT_TOKEN:}
    signingSecret: ${SLACK_SIGNING_SECRET:}
# Spring Boot Actuator - GCP uses /health
management:
    endpoints:
        web:
            exposure:
                include: health,info
    endpoint:
        health:
            show-details: always
# Server port (useful for local testing, GCP Cloud Functions can use this as well)
server:
    port: 8080
spring:
    threads:
        virtual:
            enabled: true
    # web clients that interact will LLM needs more patience
    http:
        client:
            reactive:
              read-timeout: 30s
              connect-timeout: 5s
              response-timeout: 400s
    # Claude API Configuration
    ai:
        retry:
            max-attempts: 5
        anthropic:
            api-key: ${CLAUDE_API_KEY:}
            chat:
                options:
                    model: claude-opus-4-20250514
                    temperature: 0.7
                    max-tokens: 500
        mcp:
            client:
                request-timeout: 300s
                toolcallback:
                    enabled: true
                sse:
                    connections:
                        gcptoolbox:
                            url: ${MCPTOOLBOX_URL:}
                            sse-endpoint: /mcp/sse
